
services:
  apisix:
    image: carpooling/api-gateway:latest
    container_name: apisix
    restart: always
    environment:
      APISIX_STAND_ALONE: "true"  
      APISIX_LOG_LEVEL: warn
    ports:
      - 9080:9080  # APISIX HTTP Proxy
      - 9443:9443  # APISIX HTTPS Proxy
    networks:
      - shared_network

  nginx:
    ### This is just a placeholder for the upstream service
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - shared_network

  app:
    image: carpooling/authentication:latest
    container_name: auth-service
    ports:
      - "8003:8003"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/firebase-service-account.json
    volumes:
      - ${LOCAL_FIREBASE_JSON_PATH}:/app/firebase-service-account.json

    networks:
    - shared_network

networks:
  shared_network:
    driver: bridge
