### This file is used to override the default docker-compose file for local development
services:

  apisix:
    image: apache/apisix:latest
    container_name: apisix
    restart: always
    environment:
      APISIX_STAND_ALONE: "true"  
      APISIX_CONFIG_PATH: "/usr/local/apisix/conf/apisix.yaml"
      APISIX_LOG_LEVEL: debug
    volumes: 
      # Mount the local APISIX configuration file to be make local development easier
      - ../api-gateway/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    ports:
      - 9080:9080  # APISIX HTTP Proxy
      - 9443:9443  # APISIX HTTPS Proxy, not currently enabled
      - 9180:9180  # APISIX Admin API helps in debugging
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
