receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  debug:
      verbosity: detailed  
  opensearch:
    logs_index: otel
    http:
      endpoint: "http://opensearch:9200"
      tls:
        insecure: true


service:
  pipelines:
    logs:
      receivers: [otlp]
      # processors: [batch]
      exporters: [debug, opensearch]

  telemetry:
    logs:
      level: debug
      
